### ISSUE TITLE
ERROR INIT A DOCUS/NUXT APP DUE TO rollup rollup.win32-x64-msvc.node module

### ISSUE THREAD

**Issue by vvhybe** [nuxt-themes/docus#1009]
I faced an error while waiting for the app to run from the `npm run dev` command on the test project following only the commands listed here and nothing else https://docus.dev/introduction/getting-started#create-a-new-project, 

#### Node Version On My Machine:
my node version is: `20.9.0`
```pwsh
PS C:\Users\vvhyb> node -v
v20.9.0
PS C:\Users\vvhyb>
```
![image](https://github.com/nuxt-themes/docus/assets/95445743/4ca2cfa5-f952-4aa8-9ded-a668fc9de134)

#### The First Run Error:
here is all the command and options I used from the installation start till `npm run dev`
```pwsh
PS C:\Projects> npx nuxi@latest init docs -t themes/docus

✔ Which package manager would you like to use?
npm
◐ Installing dependencies...                                                                               11:35:46 AM
npm WARN deprecated paneer@0.1.0: Please migrate to https://github.com/unjs/magicast

added 1251 packages, and audited 1253 packages in 2m

327 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✔ Installation completed.                                                                                 11:37:27 AM

✔ Initialize git repository?
Yes
ℹ Initializing git repository...                                                                          11:37:36 AM

Initialized empty Git repository in C:/Projects/docs/.git/
                                                                                                           11:37:36 AM
✨ Nuxt project has been created with the docus template. Next steps:
 › cd docs                                                                                                 11:37:36 AM
 › Start development server with npm run dev                                                               11:37:36 AM
PS C:\Projects> cd docs && npm run dev
At line:1 char:9
+ cd docs && npm run dev
+         ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

PS C:\Projects> cd docs
PS C:\Projects\docs> npm run dev

> docus-starter@0.1.0 dev
> nuxi dev

Nuxt 3.8.2 with Nitro 2.8.0                                                                                11:38:34 AM
                                                                                                           11:38:36 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose


                                       11:38:38 AMould not be found.
\\?\C:\Projects\docs\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node

  \\?\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node
  at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at Object.<anonymous> (node_modules\nitropack\node_modules\rollup\dist\native.js:60:48)
  at Module._compile (node:internal/modules/cjs/loader:1241:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)


                                      11:38:38 AM could not be found.
\\?\C:\Projects\docs\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node

  \\?\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node
  at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at Object.<anonymous> (node_modules\nitropack\node_modules\rollup\dist\native.js:60:48)
  at Module._compile (node:internal/modules/cjs/loader:1241:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)

```
I hope this helps to solve the error.

**Comment by vvhybe** [comment]
I managed to resolve this issue by following these setups: https://github.com/lerna/lerna/issues/3612#issuecomment-1538380963
