### ISSUE TITLE
bug: design tokens not read and applied correctly

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt-themes/docus#715]
Source code: https://github.com/LWSSC/documentation

How it looked before updating to `v1.1.3`:
![image](https://user-images.githubusercontent.com/43365376/206144689-d90e47b9-8a0f-409b-887a-80d1364e78b4.png)

How it looks now:
![image](https://user-images.githubusercontent.com/43365376/206144780-512ce8a2-1c09-4a0d-b402-781db2f6b285.png)

Following errors are thrown upon starting a dev/production server:
```
 ERROR  {
  filePath: '/home/aleksa/Desktop/Projects/documentation/node_modules/@nuxt-themes/elements/tokens.config.ts',
  e: TypeError: Cannot read properties of undefined (reading 'teal')
      at /home/aleksa/Desktop/Projects/documentation/node_modules/@nuxt-themes/elements/tokens.config.ts:6:36
      at jiti (/home/aleksa/Desktop/Projects/documentation/node_modules/jiti/dist/jiti.js:1:247502)
      at loadConfigFile (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:673:7)
      at resolveConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:646:14)
      at loadConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:657:30)
      at reloadConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:476:26)
      at usePinceauConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:474:15)
      at createContext (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:766:25)
      at /home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:835:17
      at Object.<anonymous> (/home/aleksa/Desktop/Projects/documentation/node_modules/unplugin/dist/index.js:1231:32)
}


 ERROR  {
  filePath: '/home/aleksa/Desktop/Projects/documentation/node_modules/@nuxt-themes/docus/tokens.config.ts',
  e: TypeError: Cannot read properties of undefined (reading 'lightblue')
      at /home/aleksa/Desktop/Projects/documentation/node_modules/@nuxt-themes/docus/tokens.config.ts:6:36
      at jiti (/home/aleksa/Desktop/Projects/documentation/node_modules/jiti/dist/jiti.js:1:247502)
      at loadConfigFile (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:673:7)
      at resolveConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:646:14)
      at loadConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:657:30)
      at reloadConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:476:26)
      at usePinceauConfig (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:474:15)
      at createContext (/home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:766:25)
      at /home/aleksa/Desktop/Projects/documentation/node_modules/pinceau/dist/shared/pinceau.8164d2d3.cjs:835:17
      at Object.<anonymous> (/home/aleksa/Desktop/Projects/documentation/node_modules/unplugin/dist/index.js:1231:32)
}
```

**Comment by Atinux** [comment]
We are sorry about this, the colors are now singular `colors` -> `color`

**Comment by Tahul** [comment]
Hey @Lexpeartha ;

https://github.com/LWSSC/documentation/pull/4

Here is a PR that fixes your project!

Really nice looking website by the way 😸

![CleanShot 2022-12-08 at 00.49.41@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_12_08_at_00_49_41_2x_af2c32bacc.png)
