### ISSUE TITLE
Error with build 1.7.0

### ISSUE THREAD

**Issue by Archetipo95** [nuxt-themes/docus#806]
ERROR  The "path" argument must be of type string. Received null

The only dependency I use are Nuxt 3.1.1 and Docus 1.7.0

**Comment by PhE** [comment]
Got the same error with 1.7.0, works fine with the previous 1.6.3

**Comment by PhE** [comment]
It also breaks the 1.6.3 on a fresh install !!!

Steps to reproduce :
```
npx nuxi@latest init docs -t themes/docus
cd docs
```

Update the `packages.json` to force docus at the  `1.6.3` version :
```json
{
  "name": "docus-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "generate": "nuxi generate",
    "preview": "nuxi preview"
  },
  "devDependencies": {
    "nuxt": "^3.1.0",
    "@nuxt-themes/docus": "=1.6.3"
  }
}
```

```
yarn install
yarn generate
```

You get the "path" error :
```
✓ 420 modules transformed.
rendering chunks (26)...The "path" argument must be of type string. Received null

 ERROR  The "path" argument must be of type string. Received null                           16:09:14

  at new NodeError (node:internal/errors:399:5)
  at validateString (node:internal/validators:163:11)
  at resolve (node:path:1102:7)
  at node_modules/rollup/dist/es/shared/rollup.js:16552:71
  at Array.map (<anonymous>)
  at getCollapsedSourcemap (node_modules/rollup/dist/es/shared/rollup.js:16552:37)
  at node_modules/rollup/dist/es/shared/rollup.js:16564:24
  at Array.map (<anonymous>)
  at collapseSourcemaps (node_modules/rollup/dist/es/shared/rollup.js:16564:10)
  at transformChunk (node_modules/rollup/dist/es/shared/rollup.js:16662:15)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/rollup/dist/es/shared/rollup.js:16695:17
  [...]
```

Please note the first lines raising `pinceau`errors that you don't get on an existing project (with a yarn.lock) :
```
yarn run v1.22.19
$ nuxi generate
Nuxi 3.1.1                                                                                  16:08:45
Nuxt 3.1.1 with Nitro 2.1.1                                                                 16:08:45
✔ Using Docus v1.6.3                                                                        16:08:47
✔ Using Nuxt Typography v0.6.0                                                              16:08:47

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.

ℹ Building client...                                                                        16:08:50

 ERROR  Pinceau could not resolve this configuration file:                               🖌  16:08:50

🔗 /home/philippe/src/docusdbg/docs/node_modules/@nuxt-themes/elements/tokens.config.ts  🖌  16:08:50

🚧 Package subpath './tokens' is not defined by "exports" in /home/philippe/src/docusdbg/docs/node_modules/@nuxt-themes/tokens/package.json


 ERROR  Pinceau could not resolve this configuration file:                               🖌  16:08:50

🔗 /home/philippe/src/docusdbg/docs/node_modules/@nuxt-themes/docus/tokens.config.ts     🖌  16:08:50

🚧 Package subpath './tokens' is not defined by "exports" in /home/philippe/src/docusdbg/docs/node_modules/@nuxt-themes/tokens/package.json

vite v4.0.4 building for production...
✔ Components metas parsed in 13009.45ms                                 nuxt-component-meta 16:09:04
✓ 438 modules transformed.
.nuxt/dist/client/manifest.json                                     79.60 kB
.nuxt/dist/client/_nuxt/ProseImg.018721e2.css                        0.05 kB │ gzip:  0.07 kB
.nuxt/dist/client/_nuxt/Container.dc145a5e.css                       0.08 kB │ gzip:  0.08 kB
.nuxt/dist/client/_nuxt/ProseEm.26a085fc.css                         0.08 kB │ gzip:  0.09 kB
.nuxt/dist/client/_nuxt/page.44ad8ca3.css                            0.08 kB │ gzip:  0.10 kB
.nuxt
```

If confirmed, it is a **critical** bug that not only break the 1.7.0 release but also the 1.6.3.

**Comment by Tahul** [comment]
Hey; this has been fixed by 1.7.1.

Sorry for this guys, having a blast this week with vuejs.amsterdam coming up.

Happy to hear if your projects are fixed by this update, if not I'll be responsive to this issue to help you out.

**Comment by PhE** [comment]
Everything is fixed, thanks !!
