### ISSUE TITLE
errors prerendering site from `mdast-util-to-hast`: `state.patch is not a function`

### ISSUE THREAD

**Issue by danielroe** [nuxt-themes/docus#861]
Encountered some issues when upgrading Nuxt Image to the latest docus version, flowing from `mdast-util-to-hast`, it seems.

<details>
<summary><strong>Build logs</strong></summary>

```
12:06:37 PM: [error] [nuxt] [request error] [unhandled] [500] state.patch is not a function
12:06:37 PM:   at defaultUnknownHandler (./node_modules/mdast-util-to-hast/lib/state.js:542:9)
12:06:37 PM:   at one (./node_modules/mdast-util-to-hast/lib/state.js:466:10)
12:06:37 PM:   at all (./node_modules/mdast-util-to-hast/lib/state.js:488:22)
12:06:37 PM:   at containerComponent (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:10559:55)
12:06:37 PM:   at one (./node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/traverse.js:56:51)
12:06:37 PM:   at all (./node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/traverse.js:81:22)
12:06:37 PM:   at root (./node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/handlers/root.js:16:41)
12:06:37 PM:   at one (./node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/traverse.js:56:51)
12:06:37 PM:   at toHast (./node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/index.js:272:16)
12:06:37 PM:   at ./node_modules/remark-rehype/lib/index.js:70:20
12:06:37 PM:   at wrapped (./node_modules/trough/index.js:115:27)
12:06:37 PM:   at next (./node_modules/trough/index.js:65:23)
12:06:37 PM:   at done (./node_modules/trough/index.js:148:7)
12:06:37 PM:   at then (./node_modules/trough/index.js:158:5)
12:06:37 PM:   at wrapped (./node_modules/trough/index.js:136:9)
12:06:37 PM:   at next (./node_modules/trough/index.js:65:23)
12:06:37 PM:   at done (./node_modules/trough/index.js:148:7)
12:06:37 PM:   at then (./node_modules/trough/index.js:158:5)
12:06:37 PM:   at wrapped (./node_modules/trough/index.js:136:9)
12:06:37 PM:   at next (./node_modules/trough/index.js:65:23)
12:06:37 PM:   at done (./node_modules/trough/index.js:148:7)
12:06:37 PM:   at then (./node_modules/trough/index.js:158:5)
12:06:37 PM:   at wrapped (./node_modules/trough/index.js:136:9)
12:06:37 PM:   at next (./node_modules/trough/index.js:65:23)
12:06:37 PM:   at Object.run (./node_modules/trough/index.js:36:5)
12:06:37 PM:   at executor (./node_modules/unified/lib/index.js:321:20)
12:06:37 PM:   at Function.run (./node_modules/unified/lib/index.js:312:5)
12:06:37 PM:   at executor (./node_modules/unified/lib/index.js:393:17)
12:06:37 PM:   at Function.process (./node_modules/unified/lib/index.js:383:5)
12:06:37 PM:   at ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:10705:12
12:06:37 PM:   at new Promise (<anonymous>)
12:06:37 PM:   at generateBody (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:10696:10)
12:06:37 PM:   at parse (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:10778:22)
12:06:37 PM:   at async Object.parse (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:10822:20)
12:06:37 PM:   at async transformContent (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:11781:18)
12:06:37 PM:   at async parseContent (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:11940:18)
12:06:37 PM:   at async getContent (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:11917:18)
12:06:37 PM:   at async Promise.all (index 0)
12:06:37 PM:   at async getContentsList (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:11881:20)
12:06:37 PM:   at async ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:9360:18
12:06:37 PM:   at async ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:12087:20
12:06:37 PM:   at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)
12:06:37 PM:   at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
12:06:37 PM:   at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
12:06:37 PM:   at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
12:06:37 PM:   at async ./.nuxt/prerender/chunks/app/server.mjs:1741:16
12:06:37 PM:   at async Promise.all (index 3)
12:06:37 PM:   at async refresh (./.nuxt/prerender/chunks/app/server.mjs:1953:12)
12:06:37 PM:   at async ./.nuxt/prerender/chunks/app/server.mjs:1991:22
12:06:37 PM:   at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)
```

</details>

**Comment by oripka** [comment]
@Atinux This fixed it for me
