### ISSUE TITLE
Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by ymarinAK** [nuxt-themes/docus#900]
Hello I build the project but I have this issues.. 

Environment:

``` json
"devDependencies": {
    "@nuxt-themes/docus": "^1.10.1",
    "@nuxt/content": "^2.5.2",
    "@nuxt/eslint-config": "^0.1.1",
    "eslint": "^8.36.0",
    "nuxt": "^3.3.1"
 }
```

Error:

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/129302545/235267912-8001c399-5299-4cda-b270-12e10fa2ecc1.png">

Can you help me.

Regards.

**Comment by mathieunicolas** [comment]
Same error here :

```
  "devDependencies": {
    "@nuxt-themes/docus": "^1.11",
    "consola": "^3.1.0",
    "nuxt": "^3.4.3",
    "rehype-katex": "^6.0.3",
    "remark-math": "^5.1.1"
  },
```

**Comment by ymarinAK** [comment]
At temporary solution is change the version `"@nuxt-themes/docus"`  to `1.10.1`.
`package.json`
``` json

```

**Comment by gbicou** [comment]
same error with

```json
{
  "@nuxt-themes/docus": "1.11.0",
  "nuxt": "3.4.3"
}
```

```
ℹ vite v4.3.4 building SSR bundle for production...                                                                                                                                                                                                       4:23:58 PM
ℹ ✓ 570 modules transformed.                                                                                                                                                                                                                              4:24:03 PM
ℹ ✓ built in 5.10s                                                                                                                                                                                                                                        4:24:03 PM

 ERROR  Identifier directly after number (Note that you need plugins to import files that are not JavaScript)                                                                                                                                             4:24:03 PM
file: /home/bicou/tmp/ndocs/docs/node_modules/.pnpm/@nuxt-themes+docus@1.11.0_nuxt@3.4.3_postcss@8.4.23_rollup@3.21.3_vue@3.2.47/node_modules/@nuxt-themes/docus/components/app/AppFooter.vue?vue&type=style&index=0&scoped=9fbef7ba&lang.ts?inline&used:1:7
1: footer{display:flex;min-height:var(--docus-footer-height);border-top-width:1px;border-top-style:solid;border-top-colo...
          ^

 ERROR  Identifier directly after number (Note that you need plugins to import files that are not JavaScript)                                                                                                                                             4:24:03 PM

  at error (node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Module.error (node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:13438:16)
  at Module.tryParse (node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:14145:25)
  at Module.setSource (node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:13747:39)
  at ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:23712:20)
```

---

but OK when downgrading nuxt to v3.4.2

```json
{
  "@nuxt-themes/docus": "1.11.0",
  "nuxt": "3.4.2"
}
```

**Comment by gbicou** [comment]
seems that v1.11.1 resolved this issue :tada: 

```json
{
  "@nuxt-themes/docus": "1.11.1",
  "nuxt": "3.4.3"
}
```

**Comment by Tahul** [comment]
Hello; this has been fixed by Nuxt `3.5.0` or Docus `^1.11.1` :)

Feel free to re-open if you encounter this issue again!
