### ISSUE TITLE
out of memory on nuxi generate

### ISSUE THREAD

**Issue by PhE** [nuxt-themes/docus#944]
I get a `JavaScript heap out of memory` when I `generate` my docus project.
No issue when I `build` or `dev`.

If I reduce the `/content` folder size the error may disappear but it is not releated to a specific content (220 files/folders for 20 Mb). I had no problem to generate this content size with previous docus/content/nuxt version.
I also tried to increase node memory limit but if fails too (export NODE_OPTIONS="--max-old-space-size=8192", seems to process more content before crashing).

The `nuxi generate` output (with the error) :
```
> npx nuxi generate
Nuxi 3.6.2
Nuxt 3.6.2 with Nitro 2.5.2
✔ Using paxpar-widgets v2.0.9
✔ Target env DEV ...
✔ Using nuxtsupabase (arundo fork !)
ℹ Using default Tailwind CSS file

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.
ℹ Building client...
ℹ vite v4.3.9 building for production...
✔ Components metas parsed in 8897.55ms
transforming (24) node_modules/nuxt/dist/app/components/nuxt-root.vue
🌼 daisyUI 3.2.1 https://daisyui.com
╰╮
 ╰─ ✔︎ [ 2 ] themes are enabled. You can add more themes or make your own theme:
      https://daisyui.com/docs/themes

    ❤︎ Support daisyUI: https://opencollective.com/daisyui
[...]
<--- Last few GCs --->

[217552:0x7492d00]    68084 ms: Mark-sweep 1975.2 (2095.4) -> 1975.2 (2095.1) MB, 256.1 / 0.0 ms  (average mu = 0.106, current mu = 0.007) allocation failure; scavenge might not succeed
[217552:0x7492d00]    68492 ms: Mark-sweep 1975.8 (2095.8) -> 1975.8 (2095.8) MB, 406.0 / 0.0 ms  (average mu = 0.047, current mu = 0.004) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7a940 node::Abort() [node]
 2: 0xa8e823  [node]
 3: 0xd5c990 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd5cd37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf3a435  [node]
 6: 0xf3b338 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xf4b843  [node]
 8: 0xf4c6b8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf2701e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xf283e7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xf08930 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
12: 0xf003a4 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
13: 0xf02738 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [node]
14: 0xf0bbec v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [node]
15: 0xd6ba43 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
16: 0xc65529 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [node]
17: 0xb4fdea  [node]
18: 0x1680f6f  [node]
Aborted (core dumped)
```

The `nuxi build` output (no error) :
```
❯ npx nuxi build
Nuxi 3.6.2                                                                                              
Nuxt 3.6.2 with Nitro 2.5.2                                                                             
✔ Using paxpar-widgets v2.0.9                                                                           
✔ Target env DEV ...                                                                                    
✔ Using nuxtsupabase (arundo fork !)                                                                    
ℹ Using default Tailwind CSS file                                                                       
ℹ Building client...                                                                                    
ℹ vite v4.3.9 building for production...                                                                
✔ Components metas parsed in 8665.84ms                                                                  
transforming (22) node_modules/@nuxt/content/dist/runtime/plugins/documentDriven.mjs
🌼 daisyUI 3.2.1 https://daisyui.com
╰╮
 ╰─ ✔︎ [ 2 ] themes are enabled. You can add more themes or make your own theme:
      https://daisyui.com/docs/themes

    ❤︎ Support daisyUI: https://opencollective.com/daisyui
[...]
  ├─ .output/server/chunks/search.mjs (2.83 kB) (1.06 kB gzip)
  ├─ .output/server/chunks/search.mjs.map (1.83 kB) (528 B gzip)
  ├─ .output/server/index.mjs (1.39 kB) (513 B gzip)
  └─ .output/server/package.json (7.15 kB) (2.09 kB gzip)
Σ Total size: 24.2 MB (4.57 MB gzip)
✔ You can preview this build using node .output/server/index.mjs
```

**Comment by Atinux** [comment]
Could you try with an older version of Nuxt by any chance?

**Comment by PhE** [comment]
Works fine with 'nuxt@3.6.1' after downgrading from 'nuxt@3.6.2' !

Not chance, pure skill  :wink:  thanks @Atinux 

I close this issue. Should I open one in nuxt project ?

**Comment by PhE** [comment]
Setting `nitro.prerender.concurrency ` to 1 prevents the memory leak (I will open an issue in nitro on that subject)

Thanks @danielroe !

...but now it fails with an error I don't have with nuxt@3.6.1.
It seems the 302/404 errors I get are fatal with nuxt@3.6.2, but not fatal with nuxt@3.6.1

```
Errors prerendering:
  ├─ /docs/team/assets/logo (302)           
  ├─ /docs/team/chave_movel_digital (302)   
  ├─ /docs/team/deploy/2022 (302)           
[...]
  ├─ /docs/documentation (404)    
  ├─ /docs/front (404)            
  ├─ /docs/back (404)             
[...]

 ERROR  Exiting due to prerender errors.                                       

  at prerender (node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:189:11)
  at async node_modules/nuxt/dist/index.mjs:2634:7
  at async build (node_modules/nuxt/dist/index.mjs:3785:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:36:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

I will open an issue in nuxt on that new subject.

**Comment by danielroe** [comment]
Yes, we now set `nitro.prerender.failOnError` to true. You can disable this or (safer) add failing routes to `nitro.prerender.ignore`.

**Comment by 0x77dev** [comment]
The issue persists, both on node and bun
